version: "3.9"

services:
  db:
    container_name: pg_container
    image: postgres
    networks:
      - my_network
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    networks:
      - my_network
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  app:
    container_name: app
    image: my_service
#    restart: always
    networks:
      - my_network
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "5001:5001"

networks:
  my_network:
    driver: bridge