version: "3.9"

services:
  db:
    container_name: pg_container
    image: postgres
    networks:
      - my_network
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  app:
    container_name: app
    image: ilyaind/mlops_hse_course
    restart: always
    networks:
      - my_network
    depends_on:
      - db
    ports:
      - "5001:5001"

networks:
  my_network:
    driver: bridge